# BEGIN ray-train-platform managed Volcengine DNS forwarding
ivolces.com:53 {
    errors
    cache 30
    forward . 100.96.0.2 100.96.0.3 {
        max_concurrent 10000
    }
}

volcengineapi.com:53 {
    errors
    cache 30
    forward . 100.96.0.2 100.96.0.3 {
        max_concurrent 10000
    }
}

tos-cn-shanghai.volces.com:53 {
    errors
    cache 30
    forward . 100.96.0.2 100.96.0.3 {
        max_concurrent 10000
    }
}
# END ray-train-platform managed Volcengine DNS forwarding
