package observability

import (
	"context"
	"crypto/hmac"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"
)

var (
	ErrJobSourceUnavailable = errors.New("verified MLflow job source is unavailable")
	ErrAmbiguousJobSource   = errors.New("job has multiple possible MLflow source runs")
)

// JobSource identifies a uniquely verified platform job run. It does not prove
// that an arbitrary file was generated by the run; the caller must independently
// authorise and verify the file's job association.
type JobSource struct {
	JobID        string `json:"jobId"`
	RunID        string `json:"runId"`
	ExperimentID string `json:"experimentId"`
}

// ResolveJobSource deliberately does not use the latest-run selection used by
// metrics views. Exporting a weight must never silently guess among job runs.
func (c *MLflowClient) ResolveJobSource(ctx context.Context, tenantID, jobID string) (JobSource, error) {
	if c == nil || strings.TrimSpace(c.BaseURL) == "" || len(c.ProvenanceKey) < 32 {
		return JobSource{}, fmt.Errorf("%w: MLflow source verification is not configured", ErrJobSourceUnavailable)
	}
	if !safeLabelValue(tenantID) || !safeLabelValue(jobID) {
		return JobSource{}, fmt.Errorf("%w: tenant or job identifier is invalid", ErrJobSourceUnavailable)
	}
	prefix := strings.Trim(strings.TrimSpace(c.ExperimentPrefix), "-")
	if prefix == "" {
		prefix = "raytrain"
	}
	if !safeLabelValue(prefix) {
		return JobSource{}, fmt.Errorf("%w: experiment prefix is invalid", ErrJobSourceUnavailable)
	}
	experimentID, found, err := c.experimentID(ctx, prefix+"-"+tenantID)
	if err != nil {
		return JobSource{}, fmt.Errorf("%w: %w", ErrJobSourceUnavailable, err)
	}
	if !found || !safeLabelValue(experimentID) {
		return JobSource{}, ErrJobSourceUnavailable
	}
	return c.uniqueJobSource(ctx, experimentID, jobID)
}

func (c *MLflowClient) uniqueJobSource(ctx context.Context, experimentID, jobID string) (JobSource, error) {
	endpoint, err := c.endpoint("/api/2.0/mlflow/runs/search")
	if err != nil {
		return JobSource{}, fmt.Errorf("%w: %w", ErrJobSourceUnavailable, err)
	}
	proof := mlflowProvenanceTag(c.ProvenanceKey, jobID)
	body := map[string]any{
		"experiment_ids": []string{experimentID},
		"filter":         "tags.`platform.job_id` = '" + jobID + "' AND tags.`platform.provenance` = '" + proof + "'",
		"max_results":    2,
	}
	var payload struct {
		Runs          []jobSourceRunResponse `json:"runs"`
		NextPageToken string                 `json:"next_page_token"`
	}
	if _, err := c.doJSON(ctx, http.MethodPost, endpoint, body, &payload); err != nil {
		return JobSource{}, fmt.Errorf("%w: %w", ErrJobSourceUnavailable, err)
	}
	if len(payload.Runs) > 1 || payload.NextPageToken != "" {
		return JobSource{}, ErrAmbiguousJobSource
	}
	if len(payload.Runs) == 0 {
		return JobSource{}, ErrJobSourceUnavailable
	}
	run := payload.Runs[0]
	if !safeLabelValue(run.Info.ID) || !run.matchesExperiment(experimentID) || !run.verifiedTags(jobID, proof) {
		return JobSource{}, ErrJobSourceUnavailable
	}
	return JobSource{JobID: jobID, RunID: run.Info.ID, ExperimentID: experimentID}, nil
}

type jobSourceRunResponse struct {
	Info struct {
		ID           string          `json:"run_id"`
		ExperimentID json.RawMessage `json:"experiment_id"`
	} `json:"info"`
	Data struct {
		Tags []struct {
			Key   string `json:"key"`
			Value string `json:"value"`
		} `json:"tags"`
	} `json:"data"`
}

func (r jobSourceRunResponse) matchesExperiment(experimentID string) bool {
	if len(r.Info.ExperimentID) == 0 {
		return true
	}
	var value string
	return json.Unmarshal(r.Info.ExperimentID, &value) == nil && value == experimentID
}

func (r jobSourceRunResponse) verifiedTags(jobID, proof string) bool {
	jobs, proofs := 0, 0
	for _, tag := range r.Data.Tags {
		switch tag.Key {
		case "platform.job_id":
			if tag.Value != jobID {
				return false
			}
			jobs++
		case "platform.provenance":
			if !hmac.Equal([]byte(tag.Value), []byte(proof)) {
				return false
			}
			proofs++
		}
	}
	return jobs == 1 && proofs == 1
}
