apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ray-cache-local.fullname" . }}
  labels:
    {{- include "ray-cache-local.labels" . | nindent 4 }}
{{- if .Values.monitoring.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ray-cache-local.fullname" . }}-monitor
  labels:
    {{- include "ray-cache-local.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
