{{- if (default false .Values.datasetPublisher.enabled) }}
{{- $publisher := .Values.datasetPublisher -}}
{{- $name := include "ray-train-platform.datasetPublisher.resourceName" (list . "") -}}
{{- $roleTRN := default "" $publisher.serviceAccount.irsaRoleTRN -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{ $name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ray-train-platform.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: dataset-publisher
  {{- with $roleTRN }}
  annotations:
    vke.volcengine.com/role-trn: {{ . | quote }}
  {{- end }}
{{- end }}
