{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ray-train-frontend
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: ray-train-frontend
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - {}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: ray-train-backend
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ray-train-backend
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: ray-train-backend
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ray-train-frontend
      ports:
        - protocol: TCP
          port: 8080
    - ports:
        - protocol: TCP
          port: 8080
  egress:
    - {}
{{- end }}
